server:
  port: 8080

spring:
  profiles:
    active:

  datasource:
    url: jdbc:postgresql://ep-withered-waterfall-aefe4e0d-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_SvEINL9jr3Ai
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: true
      path: /h2-console
